project:
  type: default
  output-dir: _jupyter
  render:
    - "*.qmd"
  pre-render:
    - "utils/render_mermaid.py"
  post-render:
    - "utils/clean_mermaid_svg.py"

execute:
  enabled: false

format:
  ipynb:
    toc: true
    wrap: none
