project:
  type: default
  output-dir: _jupyter
  render:
    - "*.qmd"
  post-render:
    - "utils/clean_attachments.py"
    - "utils/add_image_attrs.py"

execute:
  enabled: false

format:
  ipynb:
    toc: true
    wrap: none
