[project]
name = "deep-learning-notes"
version = "2026.08.24"
keywords = [
    "deep learning tutorial",
    "computer vision",
    "natural language processing",
    "large language model",
    "pytorch",
    "quarto",
    "jupyter notebook",
    "typst",
]
description = "A collection of notes and code examples for deep learning concepts and techniques."
authors = [{ name = "jshn9515", email = "jshn9510@gmail.com" }]
readme = "README.md"
license = "CC-BY-NC-4.0"
requires-python = ">=3.14,<3.15"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Operating System :: OS Independent",
    "Intended Audience :: Education",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Mathematics",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.14",
]
dependencies = [
    # Deep learning core libraries
    "accelerate>=1.14.0,<1.15.0",
    "datasets>=5.0.0,<5.1.0",
    "diffusers>=0.40.0,<0.41.0",
    "evaluate>=0.4.0,<0.5.0",
    "opt-einsum>=3.4.0,<3.5.0",
    "tokenizers>=0.23.0,<0.24.0",
    "torch>=2.13.0,<2.14.0",
    "torchaudio>=2.11.0,<2.12.0",
    "torchinfo>=1.8.0,<1.9.0",
    "torchmetrics>=1.9.0,<1.10.0",
    "torchvision>=0.28.0,<0.29.0",
    "transformers>=5.16.0,<5.17.0",

    # Jupyter and related tools
    "ipython>=9.15.0",
    "ipywidgets>=8.0.0",
    "jupyter-cache>=1.0.0",
    "jupyterlab>=4.5.0",

    # Data processing and visualization
    "matplotlib>=3.11.0,<3.12.0",
    "numpy>=2.5.0,<2.6.0",
    "pandas>=3.0.0,<3.1.0",
    "pillow>=12.3.0,<12.4.0",
    "scikit-learn>=1.9.0,<1.10.0",
    "scipy>=1.18.0,<1.19.0",

    # Data download and management
    "gdown>=6.1.0,<6.2.0",
    "pyyaml>=6.0.0,<6.1.0",

    # The auxiliary package of dnnl
    "dnnlpy==2026.08.24",
]

[project.urls]
Homepage = "https://github.com/jshn9515/deep-learning-notes"

[dependency-groups]
cpu = [
    "torch>=2.13.0,<2.14.0",
    "torchvision>=0.28.0,<0.29.0",
    "torchaudio>=2.11.0,<2.12.0",
]
cu126 = [
    "torch>=2.13.0,<2.14.0",
    "torchvision>=0.28.0,<0.29.0",
    "torchaudio>=2.11.0,<2.12.0",
]
cu130 = [
    "torch>=2.13.0,<2.14.0",
    "torchvision>=0.28.0,<0.29.0",
    "torchaudio>=2.11.0,<2.12.0",
]
cu132 = [
    "torch>=2.13.0,<2.14.0",
    "torchvision>=0.28.0,<0.29.0",
    "torchaudio>=2.11.0,<2.12.0",
]
xpu = [
    "torch>=2.13.0,<2.14.0",
    "torchvision>=0.28.0,<0.29.0",
    "torchaudio>=2.11.0,<2.12.0",
]

[tool.uv]
torch-backend = "auto"
conflicts = [
    [
        { group = "cpu" },
        { group = "cu126" },
        { group = "cu130" },
        { group = "cu132" },
        { group = "xpu" },
    ],
]
find-links = ["https://download.pytorch.org/whl/xpu/triton-xpu"]

[tool.uv.sources]
torch = [
    { index = "pytorch-cpu", group = "cpu" },
    { index = "pytorch-cu126", group = "cu126" },
    { index = "pytorch-cu130", group = "cu130" },
    { index = "pytorch-cu132", group = "cu132" },
    { index = "pytorch-xpu", group = "xpu" },
]
torchvision = [
    { index = "pytorch-cpu", group = "cpu" },
    { index = "pytorch-cu126", group = "cu126" },
    { index = "pytorch-cu130", group = "cu130" },
    { index = "pytorch-cu132", group = "cu132" },
    { index = "pytorch-xpu", group = "xpu" },
]
dnnlpy = { workspace = true }

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[[tool.uv.index]]
name = "pytorch-cu126"
url = "https://download.pytorch.org/whl/cu126"
explicit = true

[[tool.uv.index]]
name = "pytorch-cu130"
url = "https://download.pytorch.org/whl/cu130"
explicit = true

[[tool.uv.index]]
name = "pytorch-cu132"
url = "https://download.pytorch.org/whl/cu132"
explicit = true

[[tool.uv.index]]
name = "pytorch-xpu"
url = "https://download.pytorch.org/whl/xpu"
explicit = true

[tool.uv.workspace]
members = ["dnnlpy"]
