---
config:
  startOnLoad: false
  theme: base
  htmlLabels: false
  fontFamily: Arial, Microsoft YaHei, Noto Serif CJK SC, sans-serif
  themeVariables:
    fontSize: 20px
    primaryColor: "#e9f2fc"
    primaryBorderColor: "#296bb7"
    primaryTextColor: "#333333"
    lineColor: "#0b0b0b"

  flowchart:
    wrappingWidth: 300

  themeCSS: |
    .node text,
    .nodeLabel,
    .label text {
      font-weight: 400;
      font-style: normal;
    }

    .node rect,
    .flowchart-link {
      stroke-width: 1px;
    }
---

flowchart TD
    A["FSDP Model / Optimizer"] --> B["get_state_dict()"]
    B --> C["Distributed State Dict"]
    C --> D["Save Planner"]
    D --> E["StorageWriter"]
    E --> F["Shards + Metadata"]

    G["Shards + Metadata"] --> H["StorageReader"]
    H --> I["Load Planner"]
    I --> J["Current Sharding Layout"]
    J --> K["set_state_dict()"]
    K --> L["FSDP Model / Optimizer"]
