---
config:
  startOnLoad: false
  theme: base
  htmlLabels: false
  fontFamily: Arial, Microsoft YaHei, Noto Serif CJK SC, sans-serif
  themeVariables:
    fontSize: 16px
    primaryColor: "#e9f2fc"
    primaryBorderColor: "#296bb7"
    primaryTextColor: "#333333"
    lineColor: "#0b0b0b"
  
  flowchart:
    wrappingWidth: 300

  themeCSS: |
    .node text,
    .nodeLabel,
    .label text {
      font-weight: 400;
      font-style: normal;
    }

    .node rect,
    .flowchart-link {
      stroke-width: 1px;
    }
---

flowchart TD
    A[所有 Rank 启动]
    B[初始化 Process Group]
    C[重新构造相同模型]
    D[加载同一个 Model Checkpoint]
    E[DDP Wrap]
    F[恢复 Optimizer]
    G[继续训练]

    A --> B --> C --> D --> E --> F --> G
