---
config:
  theme: base
  themeVariables:
    fontSize: "18px"
    primaryColor: "#e9f2fc"
    primaryBorderColor: "#296bb7"
    secondaryBorderColor: "#296bb7"
---

flowchart LR
  x((x)) --> mul[mul]
  y((y)) --> mul
  mul --> z((z))
  z --> sin[sin]
  sin --> f((f))
