---
config:
  startOnLoad: false
  theme: base
  htmlLabels: false
  fontFamily: Arial, Microsoft YaHei, Noto Serif CJK SC, sans-serif
  themeVariables:
    fontSize: 16px
    primaryColor: "#e9f2fc"
    primaryBorderColor: "#296bb7"
    primaryTextColor: "#333333"
    lineColor: "#0b0b0b"

  themeCSS: |
    .node text,
    .nodeLabel,
    .label text {
      font-weight: 400;
      font-style: normal;
    }

    .node rect,
    .flowchart-link {
      stroke-width: 1px;
    }
---

flowchart TD
    A[DDP]
    B[ZeRO-1]
    C[ZeRO-2]
    D[ZeRO-3 / Fully Sharded Data Parallel]

    A -->|Shard optimizer states| B
    B -->|Shard gradients| C
    C -->|Shard parameters| D
